server:
  port: 8081

spring:
  application:
    name: restore-user-service
  profiles:
    active: local

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/token/introspect
          client-id: ${keycloak.client-id}
          client-secret: ${keycloak.client-secret}

  datasource:
    url: jdbc:postgresql://localhost:5432/restore_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 1
    minimum-idle: 5

  liquibase:
    change-log: classpath:db/master.yaml
    enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
    notification:
      url: http://localhost:8002/

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Once we create common keycloak setup then we will move below conf to the config properties repo.
keycloak:
  realm: development
  base-url: https://localhost:8090/
  auth-url: ${keycloak.base-url}/
  client-id: restore-dev
  client-secret: secret-key

springdoc:
  swagger-ui:
    path: /api/user/swagger-ui.html
  api-docs:
    path: /api/user/api-docs
  show-actuator: true

